spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.runsing.springcloud.entity
    mapper-locations:
        - classpath:mybatis/mapper/**/*.xml
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://127.0.0.1:3306/clouddb01
        username: root
        password: 12qazwsx
        dbcp2: 
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
eureka:
    client: 
        service-url: 
            defaultZone: http://127.0.0.1:7001/eureka/
        instance: 
            instance-id: dept-8001.com
---
server:
    port: 8001
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.runsing.springcloud.entity
    mapper-locations:
        - classpath:mybatis/mapper/**/*.xml
spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://127.0.0.1:3306/clouddb02
        username: root
        password: 12qazwsx
        dbcp2: 
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
eureka:
    client: 
        service-url: 
            defaultZone: http://127.0.0.1:7001/eureka/
    instance: 
        instance-id: dept-8001.com